[tool.poetry]
name = "jstanek"
version = "0.1.0"
description = ""
authors = ["Jaroslav StanÄ›k <jaroslav-stanek@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.101.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
